# Generated by Django 3.2.12 on 2022-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preco')),
                ('estoque', models.IntegerField(verbose_name='qtd_em_estoque')),
            ],
        ),
    ]
