# Generated by Django 3.2.12 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=128, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=128, verbose_name='nome'),
        ),
    ]
